# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  github-release: h-matsuo/github-release@0.1.3
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:latest
      #- image: circleci/golang:latest
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/correctinator

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    #executor: github-release/default

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      #- run: mvn integration-test

      - run:
          command: |
            VERSION=$(mvn -s .circleci/settings.xml -q \
              -Dexec.executable="echo" -Dexec.args='${project.version}' \
              --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
            mkdir workspace
            mkdir workspace/artifacts
            echo "$VERSION" > workspace/version
          name: Read version from maven

      - run: mvn clean install
      - store_artifacts:
          path: artifacts/
          destination: workspace/artifacts/

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: workspace
          # Must be relative path from root
          paths:
            - artifacts/*.jar
            - version
  deploy:
    executor: github-release/default
    working_directory: ~/correctinator
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/correctinator/workspace
      - run:
          command: |
            echo 'export VERSION=$(cat ~/correctinator/workspace/version)' >> $BASH_ENV
            echo $VERSION
          name: Getting version from build-phase

      - github-release/create:
          tag: $VERSION
          title: v$VERSION
          description: This release is version v$VERSION.
          file-path: ~/correctinator/workspace/artifacts
          pre-release: true

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master