# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  github-release: h-matsuo/github-release@0.1.3
jobs:
  build:
    docker:
      # specify the version you desire here
      #- image: circleci/openjdk:latest
      #- image: circleci/golang:1.9.6
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/correctinator

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    #executor: github-release/default

    steps:
      - github-release/create:
          tag: ${VERSION}
          title: v${VERSION}
          description: This release is version v${VERSION}.
          file-path: artifacts/
          pre-release: true
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      #- run: mvn integration-test

      - run: mvn clean install
      - store_artifacts:
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: artifacts/

      - run:
          command: |
            VERSION=$(mvn -s .circleci/settings.xml -q \
              -Dexec.executable="echo" -Dexec.args='${project.version}' \
              --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
            echo "Releasing $VERSION"

        #workaround
      #- run: sudo apt install golang-go
      #- run: export GOPATH=~/go
      #- run: export PATH=$PATH:$GOPATH/bin
      #- run: go get github.com/aktau/github-release github.com/tcnksm/ghr

